class_names = [
    "Apple___Apple_scab", "Apple___Black_rot", "Apple___Cedar_apple_rust", "Apple___healthy",
    "Blueberry___healthy",
    "Cherry_(including_sour)___Powdery_mildew", "Cherry_(including_sour)___healthy",
    "Corn_(maize)___Cercospora_leaf_spot Gray_leaf_spot", "Corn_(maize)___Common_rust_",
    "Corn_(maize)___Northern_Leaf_Blight", "Corn_(maize)___healthy",
    "Grape___Black_rot", "Grape___Esca_(Black_Measles)", "Grape___Leaf_blight_(Isariopsis_Leaf_Spot)", "Grape___healthy",
    "Orange___Haunglongbing_(Citrus_greening)",
    "Peach___Bacterial_spot", "Peach___healthy",
    "Pepper,_bell___Bacterial_spot", "Pepper,_bell___healthy",
    "Potato___Early_blight", "Potato___Late_blight", "Potato___healthy",
    "Raspberry___healthy",
    "Soybean___healthy",
    "Squash___Powdery_mildew",
    "Strawberry___Leaf_scorch", "Strawberry___healthy",
    "Tomato___Bacterial_spot", "Tomato___Early_blight", "Tomato___Late_blight",
    "Tomato___Leaf_Mold", "Tomato___Septoria_leaf_spot", "Tomato___Spider_mites Two-spotted_spider_mite",
    "Tomato___Target_Spot", "Tomato___Tomato_Yellow_Leaf_Curl_Virus",
    "Tomato___Tomato_mosaic_virus", "Tomato___healthy"
]

solutions = {
    "Apple___Apple_scab": "Apply fungicides and remove fallen leaves to prevent spore spread.",
    "Apple___Black_rot": "Prune infected branches and use Captan-based fungicides.",
    "Apple___Cedar_apple_rust": "Remove nearby cedar galls and apply sulfur-based fungicides.",
    "Apple___healthy": "Plant is healthy. Maintain regular watering and fertilization.",
    "Blueberry___healthy": "Plant is healthy. Monitor soil acidity (pH) levels regularly.",
    "Cherry_(including_sour)___Powdery_mildew": "Use neem oil or potassium bicarbonate sprays in the evening.",
    "Cherry_(including_sour)___healthy": "Plant is healthy. Ensure proper sunlight and pruning.",
    "Corn_(maize)___Cercospora_leaf_spot Gray_leaf_spot": "Follow crop rotation and maintain balanced nitrogen levels.",
    "Corn_(maize)___Common_rust_": "Plant resistant varieties and apply fungicides at the first sign of spots.",
    "Corn_(maize)___Northern_Leaf_Blight": "Destroy infected crop residue and apply Mancozeb fungicides.",
    "Corn_(maize)___healthy": "Plant is healthy. Ensure adequate spacing for airflow.",
    "Grape___Black_rot": "Keep vines off the ground and use copper-based sprays.",
    "Grape___Esca_(Black_Measles)": "Avoid over-watering and prune away old, infected wood.",
    "Grape___Leaf_blight_(Isariopsis_Leaf_Spot)": "Apply Bordeaux mixture and keep the vineyard floor clean.",
    "Grape___healthy": "Plant is healthy. Continue routine pruning and support.",
    "Orange___Haunglongbing_(Citrus_greening)": "Control psyllid insects; unfortunately, infected trees may need removal.",
    "Peach___Bacterial_spot": "Apply copper bactericides and avoid excessive nitrogen fertilization.",
    "Peach___healthy": "Plant is healthy. Prune after harvest to maintain shape.",
    "Pepper,_bell___Bacterial_spot": "Use copper sprays and avoid touching wet foliage.",
    "Pepper,_bell___healthy": "Plant is healthy. Keep soil moisture consistent.",
    "Potato___Early_blight": "Practice crop rotation and remove lower infected leaves.",
    "Potato___Late_blight": "Apply copper fungicides and ensure proper soil hilling.",
    "Potato___healthy": "Plant is healthy. Monitor for pests regularly.",
    "Raspberry___healthy": "Plant is healthy. Use mulch to keep roots cool.",
    "Soybean___healthy": "Plant is healthy. Scout for bean leaf beetles.",
    "Squash___Powdery_mildew": "Spray a mix of milk and water (1:9) or use sulfur dust.",
    "Strawberry___Leaf_scorch": "Remove infected leaves and water at the base, not on the leaves.",
    "Strawberry___healthy": "Plant is healthy. Use straw mulch to keep berries off the soil.",
    "Tomato___Bacterial_spot": "Apply copper-based fungicides and use treated seeds.",
    "Tomato___Early_blight": "Spray neem oil and remove heavily infected lower branches.",
    "Tomato___Late_blight": "Use fungicides and avoid overhead watering; keep leaves dry.",
    "Tomato___Leaf_Mold": "Increase air circulation through pruning and reduce humidity.",
    "Tomato___Septoria_leaf_spot": "Avoid splashing water on leaves and use Chlorothalonil fungicide.",
    "Tomato___Spider_mites Two-spotted_spider_mite": "Wash off mites with a strong water stream or use miticides.",
    "Tomato___Target_Spot": "Apply copper or Chlorothalonil sprays every 7-10 days.",
    "Tomato___Tomato_Yellow_Leaf_Curl_Virus": "Control whiteflies and use reflective silver mulches.",
    "Tomato___Tomato_mosaic_virus": "Uproot and burn infected plants; wash hands after handling.",
    "Tomato___healthy": "Plant is healthy! Your tomato crop is in excellent condition."
}